### ISSUE TITLE
Tests for Assok

### ISSUE THREAD

**Issue by IBRAGIM-OSKANOV** [SashaErkhov/Containers#47]
Test for binarySearch and data structure

**Comment by SashaErkhov** [comment]
Добавил костяк. Осталось написать сами тесты и исправить Assoc( оно даже не хочет собираться)

**Comment by SashaErkhov** [comment]
Давай, делай уже чтоб работало, хочу защитить там ветку( и не только там)
@IBRAGIM-OSKANOV
