### ISSUE TITLE
поправить insert в List

### ISSUE THREAD

**Issue by SashaErkhov** [SashaErkhov/Containers#50]

**Comment by SashaErkhov** [comment]
А что там не так?
@77maxikov 
@IBRAGIM-OSKANOV

**Comment by IBRAGIM-OSKANOV** [comment]
@SashaErkhov 
@77maxikov
Я думаю что там все в порядке с Insert, хоть скорость O(N) напрягает.
А вот в Arry.h есть проблема с insert, он даже не компилируется.

**Comment by IBRAGIM-OSKANOV** [comment]
@SashaErkhov 
Теперь insert в Arry работает. Предлагаю закрыть этот isuue

**Comment by SashaErkhov** [comment]
Ща тесты напишу и сам закрою @IBRAGIM-OSKANOV
